version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: aprendizadopython
    environment:
      - APP_NAME=mySelfWorking
      - REDIS_URL=redis://redis:6379
      - COHERE_API_KEY=<A SUA CHAVE API>
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis/redis-stack-server:latest
    container_name: aprendizadopython-redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data: